<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Scalability TEST site, generated by gen-test-site.sh.
     Placeholders replaced: @@PUT_GROUPID@@ @@PUT_ARTIFACTID@@ @@PUT_VERSION@@ @@PUT_TYPE@@ -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>lutece-site-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece</groupId>
    <artifactId>scalability-test-site</artifactId>
    <packaging>lutece-site</packaging>
    <name>scalability-test-site</name>
    <version>1.0.0-SNAPSHOT</version>
    <description>Minimal site to test a Lutece v8 plugin scalability in a 3-instance cluster.</description>

    <repositories>
        <repository>
            <snapshots><enabled>true</enabled></snapshots>
            <id>luteceSnapshot</id><name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
        </repository>
        <repository>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>false</enabled></snapshots>
            <id>lutece</id><name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>[8.0.0,)</version>
            <type>lutece-core</type>
        </dependency>

        <!-- ===== PLUGIN UNDER TEST ===== -->
        <dependency>
            <groupId>@@PUT_GROUPID@@</groupId>
            <artifactId>@@PUT_ARTIFACTID@@</artifactId>
            <version>@@PUT_VERSION@@</version>
            <type>@@PUT_TYPE@@</type>
        </dependency>
        <!-- ============================ -->

        <!-- FO authentication — UNCOMMENT when the flow under test needs a logged-in
             LuteceUser; see harness README "FO authentication" for the seed + enable steps.
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-mylutece</artifactId>
            <version>5.0.1-SNAPSHOT</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-mylutece-database</artifactId>
            <version>7.0.1-SNAPSHOT</version>
            <type>lutece-plugin</type>
        </dependency>
        -->

        <!-- Liquibase: builds the schema (core + plugin) on first boot; DATABASECHANGELOGLOCK serialises the instances.
             It honours the "lutece runAfter:<plugin>" SQL ordering directive. -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-liquibase</artifactId>
            <version>2.0.2-SNAPSHOT</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.version}</version>
        </dependency>
        <!-- Distributed cache + session (level 2) -->
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-health</artifactId>
            <version>1.0.0</version>
            <type>lutece-plugin</type>
            <scope>runtime</scope>
        </dependency>
        <!-- Keeps a single SLF4J provider in the war: slf4j-jdk14 from the container-runtime profile. -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
