<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Scalability TEST site, generated by gen-test-site.sh.
     Placeholders replaced: @@PUT_GROUPID@@ @@PUT_ARTIFACTID@@ @@PUT_VERSION@@ @@PUT_TYPE@@ -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>lutece-site-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece</groupId>
    <artifactId>scalability-test-site</artifactId>
    <packaging>lutece-site</packaging>
    <name>scalability-test-site</name>
    <version>1.0.0-SNAPSHOT</version>
    <description>Minimal site to test a Lutece v8 plugin scalability in a 3-instance cluster.</description>

    <repositories>
        <repository>
            <snapshots><enabled>true</enabled></snapshots>
            <id>luteceSnapshot</id><name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
        </repository>
        <repository>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>false</enabled></snapshots>
            <id>lutece</id><name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>fr.paris.lutece.starters</groupId>
                <artifactId>lutece-bom</artifactId>
                <version>8.0.0-SNAPSHOT</version>
                <scope>import</scope><type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <type>lutece-core</type>
        </dependency>

        <!-- ===== PLUGIN UNDER TEST ===== -->
        <dependency>
            <groupId>@@PUT_GROUPID@@</groupId>
            <artifactId>@@PUT_ARTIFACTID@@</artifactId>
            <version>@@PUT_VERSION@@</version>
            <type>@@PUT_TYPE@@</type>
        </dependency>
        <!-- ============================ -->

        <!-- Provides core_style/core_stylesheet/core_style_mode_stylesheet, absent from
             core v8 but required by some plugins' core SQL (e.g. plugin-mylutece);
             without it the whole Liquibase migration aborts -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-xmltransformer</artifactId>
            <version>[2.0.0,)</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- FO authentication — UNCOMMENT when the flow under test needs a logged-in
             LuteceUser; see harness README "FO authentication" for the seed + enable steps.
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-mylutece</artifactId>
            <version>[5.0.0,)</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-mylutece-database</artifactId>
            <version>[7.0.0,)</version>
            <type>lutece-plugin</type>
        </dependency>
        -->

        <!-- Liquibase: builds the schema (core + plugin) on first boot; DATABASECHANGELOGLOCK serialises the instances -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-liquibase</artifactId>
            <version>2.0.0</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.5.8</version>
        </dependency>
        <!-- Distributed cache + session (level 2) -->
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>5.5.0</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>liberty</id>
            <activation><activeByDefault>true</activeByDefault></activation>
            <dependencies>
                <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-to-jul</artifactId><scope>runtime</scope></dependency>
                <dependency><groupId>org.slf4j</groupId><artifactId>slf4j-jdk14</artifactId><version>1.7.36</version><scope>runtime</scope></dependency>
                <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-core</artifactId><scope>provided</scope></dependency>
                <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-slf4j-impl</artifactId><scope>provided</scope></dependency>
                <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-jakarta-web</artifactId><scope>provided</scope></dependency>
                <dependency><groupId>fr.paris.lutece.plugins</groupId><artifactId>plugin-health</artifactId><type>lutece-plugin</type><scope>runtime</scope></dependency>
            </dependencies>
        </profile>
    </profiles>
</project>
