<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- e2e v7 site generated by tools/gen-site7.sh from pom.xml.tpl; do not edit. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>lutece-site-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>@@SITE_POM_VERSION@@</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece</groupId>
    <artifactId>e2e-site7</artifactId>
    <packaging>lutece-site</packaging>
    <name>e2e-site7</name>
    <version>1.0.0-SNAPSHOT</version>
    <description>Disposable Lutece 7 site assembling the artefact before its migration, for the before/after comparison.</description>

    <repositories>
        <repository>
            <snapshots><enabled>true</enabled></snapshots>
            <id>luteceSnapshot</id><name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
        </repository>
        <repository>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>false</enabled></snapshots>
            <id>lutece</id><name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>@@CORE_VERSION@@</version>
            <type>lutece-core</type>
        </dependency>
@@DEPENDENCIES@@
        <!-- The Ant build under WEB-INF/sql looks for this connector by name in WEB-INF/lib. -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.26</version>
        </dependency>
    </dependencies>

</project>
