<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- e2e test site generated by tools/gen-site.sh from pom.xml.tpl; do not edit. -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <artifactId>lutece-site-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece</groupId>
    <artifactId>e2e-site</artifactId>
    <packaging>lutece-site</packaging>
    <name>e2e-site</name>
    <version>1.0.0-SNAPSHOT</version>
    <description>Disposable site assembling the artefact under test for the e2e bench.</description>

    <repositories>
        <repository>
            <snapshots><enabled>true</enabled></snapshots>
            <id>luteceSnapshot</id><name>luteceSnapshot</name>
            <url>https://dev.lutece.paris.fr/snapshot_repository</url>
        </repository>
        <repository>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>false</enabled></snapshots>
            <id>lutece</id><name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>@@CORE_VERSION@@</version>
            <type>lutece-core</type>
        </dependency>
@@DEPENDENCIES@@
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-liquibase</artifactId>
            <version>@@LIQUIBASE_VERSION@@</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>${mariadb.version}</version>
        </dependency>
    </dependencies>

</project>
