#!/usr/bin/env bash
# Checks the house template rules (template_rules.py, scanner TD55/TD56) and verify-migration's DA02 and I18N07 on
# small synthetic inputs: each rule must flag its bad case and leave its good case alone.
set -u
HERE=$(cd "$(dirname "$0")" && pwd)
S="$HERE/../../skills/lutece-migration-v8-agent-teams/scripts"
T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
fail=0
expect() {
    local what=$1 want=$2 got=$3
    if [ "$want" = "$got" ]; then echo "  ok   $what"; else echo "  FAIL $what (expected $want, got $got)"; fail=1; fi
}
rule() { python3 "$S/template_rules.py" "$1" "$2" >/dev/null; echo $?; }

A="$T/admin.html"
printf "<@tform action='x'><@row><@columns md=4><@input name='a' /></@columns><@columns md=4><@input name='b' /></@columns><@columns md=4><@input name='c' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: three field columns in a row" 1 "$(rule inline-forms "$A")"
printf "<@tform action='x'><@row><@columns md=6><@input name='a' /></@columns><@columns md=6><@input name='b' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: two field columns are fine" 0 "$(rule inline-forms "$A")"
printf "<@tform action='x'><@row><@columns md=6><@input name='a' /></@columns><@columns md=6><@input name='b' /></@columns><@columns md=6><@input name='c' /></@columns><@columns md=6><@input name='d' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: four md=6 columns wrap two per line" 0 "$(rule inline-forms "$A")"
printf "<@tform action='x'><@row><@columns md=6><@row><@columns md=6><@input name='a' /></@columns><@columns md=6><@input name='b' /></@columns></@row></@columns><@columns md=6><@input name='c' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: a nested row is not counted in the outer one" 0 "$(rule inline-forms "$A")"
printf "<@tform action='x'><@row><@columns md=4><@input name='a' /></@columns><@columns md=4><@input name='b' /></@columns><@columns md=4><@input name='c' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: three md=4 field columns" 1 "$(rule inline-forms "$A")"
printf "<@tform action='x'><@row><@columns md=4><@checkBox name='a' /></@columns><@columns md=4><@checkBox name='b' /></@columns><@columns md=4><@checkBox name='c' /></@columns></@row></@tform>\n" > "$A"
expect "inline-forms: a grid of switches is fine" 0 "$(rule inline-forms "$A")"
printf "<@tform action='x' class='d-flex flex-column'><@input name='a' /><@input name='b' /><@input name='c' /></@tform>\n" > "$A"
expect "inline-forms: d-flex flex-column stacks the fields" 0 "$(rule inline-forms "$A")"
printf "<@tform type='inline' action='x'><@input name='a' /><@input name='b' /><@input name='c' /></@tform>\n" > "$A"
expect "inline-forms: type inline with three fields" 1 "$(rule inline-forms "$A")"
printf "<@tform type='inline' action='x'><@input type='hidden' name='id' /><@button type='submit' title='Export' /></@tform>\n" > "$A"
expect "inline-forms: hidden form with one submit" 0 "$(rule inline-forms "$A")"
printf "<@offcanvas id='x' title='t'>body</@offcanvas>\n" > "$A"
expect "offcanvas: flagged" 1 "$(rule offcanvas "$A")"

W="$T/proj"
J="$T/java"
mkdir -p "$W/webapp/WEB-INF/templates/admin/plugins/x" "$J/src/java/x/business" "$J/src/java/x/resources"
td() { (cd "$W" && python3 "$S/scan-template-design.py" . --flat --no-exploded 2>/dev/null | grep -c " $1 "); }
printf "<@pageContainer><@aButton href='jsp/admin/plugins/x/ManageX.jsp' title='#i18n{portal.util.labelCancel}' /></@pageContainer>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD56: cancel without colour" 1 "$(td TD56)"
printf "<@pageContainer><@aButton href='jsp/admin/plugins/x/ManageX.jsp' title='#i18n{portal.util.labelCancel}' color='light' /></@pageContainer>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD56: cancel in light" 0 "$(td TD56)"
printf "<@pageContainer><#if l?has_content>x<#else><@empty title='a' /></#if></@pageContainer>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD55: empty state without subtitle, no create action" 1 "$(td TD55)"
printf "<@pageContainer><@aButton href='jsp/admin/plugins/x/ManageX.jsp?view=createX' buttonIcon='plus' title='a' /><@empty /></@pageContainer>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD55: page with a create action" 0 "$(td TD55)"

printf "<@tform action='x'><@box><@boxBody>a</@boxBody><@boxFooter><@button type='submit' title='ok' /></@boxFooter></@box><@box><@boxBody>b</@boxBody></@box></@tform>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD58: submit in one box footer of a two-box form" 1 "$(td TD58)"
printf "<@tform action='x'><@box><@boxBody>a</@boxBody></@box><@box><@boxBody>b</@boxBody></@box><@row><@button type='submit' title='ok' /></@row></@tform>\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD58: actions below the boxes" 0 "$(td TD58)"
X="$W/webapp/WEB-INF/templates/admin/plugins/x"
printf "<@tform action='x'><@input type='textarea' name='c' /></@tform>\n<#include \"/admin/util/editor/editor.html\" />\n<@initEditor />\n" > "$X/a.html"
expect "TD59: editor without rich textarea" 1 "$(td TD59)"
printf "<@tform action='x'><@input type='textarea' name='c' richtext=true /></@tform>\n<@initEditor />\n" > "$X/a.html"
expect "TD59: rich textarea" 0 "$(td TD59)"
printf "<#macro richBox><@input type='textarea' name='c' richtext=true /></#macro>\n" > "$X/commons.html"
printf "<#include \"commons.html\" />\n<@richBox />\n<@initEditor type='comment' />\n" > "$X/a.html"
expect "TD59: rich textarea from a local macro" 0 "$(td TD59)"
rm -f "$X/commons.html"
printf "<@tform action='x'><@radioButton labelFor='n' labelKey='Nouvelle capacit\xc3\xa9' name='c' id='n' value='n' /></@tform>\n" > "$X/a.html"
expect "TD36: literal labelKey" 1 "$(td TD36)"
printf "<@tform action='x'><@radioButton labelFor='n' labelKey='#i18n{x.label}' name='c' id='n' value='n' /></@tform>\n" > "$X/a.html"
expect "TD36: i18n labelKey" 0 "$(td TD36)"
printf "<@tform action='x'><@input name='a' /><!-- <@button type='submit' title='ok' /> --></@tform>\n" > "$X/a.html"
expect "TD60: submit button inside an HTML comment" 1 "$(td TD60)"
printf "<@tform action='x'><@input name='a' /><#-- <@button type='submit' title='ok' /> --><!-- a note --></@tform>\n" > "$X/a.html"
expect "TD60: FreeMarker comment and plain HTML comment" 0 "$(td TD60)"

V="$T/assembled"
L="$V/target/lutece"
mkdir -p "$V/webapp/WEB-INF/templates/admin/plugins/x" "$L/WEB-INF/templates/admin/themes/tabler" "$L/WEB-INF/templates/skin/themes/macros" "$L/WEB-INF/plugins" "$L/themes/shared/plugins/x/js"
mkdir -p "$L/WEB-INF/templates/admin/themes/tabler/forms/checkbox"
touch "$L/WEB-INF/plugins/x.xml" "$L/themes/shared/plugins/x/js/x.js" "$L/WEB-INF/templates/admin/themes/tabler/forms/checkbox/checkBox.ftl"
tda() { (cd "$V" && python3 "$S/scan-template-design.py" . --flat 2>/dev/null | grep -c " $1 "); }
printf "<script src=\"js/admin/plugins/x/x.js\"></script>\n" > "$V/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD61: script path the assembled webapp does not carry" 1 "$(tda TD61)"
printf "<script src=\"themes/shared/plugins/x/js/x.js\"></script>\n<#if hasMap><script src=\"js/plugins/leaflet/leaflet.js\"></script></#if>\n" > "$V/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD61: carried script, and a script of an optional plugin" 0 "$(tda TD61)"

mkdir -p "$W/webapp/WEB-INF/plugins" "$W/webapp/themes/admin/x/css"
echo "<plug-in><admin-css-stylesheets><admin-css-stylesheet>themes/admin/x/css/x.css</admin-css-stylesheet></admin-css-stylesheets></plug-in>" > "$W/webapp/WEB-INF/plugins/x.xml"
printf "#id_form { max-width: 32rem; }\n" > "$W/webapp/themes/admin/x/css/x.css"
expect "TD57: generic id in a stylesheet loaded on every page" 1 "$(td TD57)"
printf ".x-plugin #id_form { max-width: 32rem; }\n#x-chart-list { margin: 0; }\n" > "$W/webapp/themes/admin/x/css/x.css"
expect "TD57: rules scoped to the plugin" 0 "$(td TD57)"

printf "<@button type='submit' title='#i18n{portal.util.labelValidate}' />\n<@aButton href='x' title='#i18n{portal.util.labelBack}' color='secondary' />\n<@aButton href='x' title='#i18n{portal.util.labelCancel}' />\n<@button cancel=true title='#i18n{portal.util.labelCancel}' />\n" > "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html"
expect "TD56 before fix-button-colours" 1 "$(td TD56)"
python3 "$S/fix-button-colours.py" "$W" > /dev/null
expect "TD51 secondary and cancel=true made light" 2 "$(grep -cE "color='secondary'|cancel=true title='#i18n\{portal.util.labelCancel\}' color='light'|labelBack\}' color='light'" "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html")"
expect "TD56 after fix-button-colours" 0 "$(td TD56)"
expect "submit button left as it is" 1 "$(grep -c "type='submit' title='#i18n{portal.util.labelValidate}' />" "$W/webapp/WEB-INF/templates/admin/plugins/x/a.html")"
expect "fix-button-colours is idempotent" 0 "$(python3 "$S/fix-button-colours.py" "$W" | wc -l)"

vm() { (cd "$J" && bash "$S/verify-migration.sh" . 2>/dev/null | grep "\[$1\]" | grep -c "$2"); }
printf 'class XDAO {\n    public void f( Plugin plugin )\n    {\n        DAOUtil daoUtil = new DAOUtil( SQL, plugin );\n        daoUtil.executeUpdate( );\n    }\n}\n' > "$J/src/java/x/business/XDAO.java"
expect "DA02: DAOUtil outside try-with-resources" 1 "$(vm DA02 FAIL)"
printf 'class XDAO {\n    private DAOUtil build( Plugin plugin )\n    {\n        DAOUtil daoUtil = new DAOUtil( SQL, plugin );\n        daoUtil.setInt( 1, 2 );\n        return daoUtil;\n    }\n}\n' > "$J/src/java/x/business/XDAO.java"
expect "DA02: factory returning its DAOUtil" 1 "$(vm DA02 PASS)"
printf 'message.confirm=Etes vous sur de vouloir supprimer ce PollFormQuestion ?\n' > "$J/src/java/x/resources/x_messages_fr.properties"
expect "I18N07: French spelling error" 1 "$(vm I18N07 WARN)"
printf 'message.confirm=\\u00cates-vous s\\u00fbr de vouloir supprimer ce graphique ?\n' > "$J/src/java/x/resources/x_messages_fr.properties"
expect "I18N07: correct French" 1 "$(vm I18N07 PASS)"

mkdir -p "$J/webapp/jsp/admin/plugins/x" "$J/src/java/x/web"
printf '${ xPortletJspBean.init( pageContext.request, "R" ) }\n' > "$J/webapp/jsp/admin/plugins/x/CreatePortletX.jsp"
printf 'public abstract class AbstractXPortletJspBean extends PortletJspBean\n{\n}\n' > "$J/src/java/x/web/AbstractXPortletJspBean.java"
printf 'public class XPortletJspBean extends AbstractXPortletJspBean\n{\n}\n' > "$J/src/java/x/web/XPortletJspBean.java"
expect "JS04: portlet bean through a local base class" 1 "$(vm JS04 PASS)"
printf 'public abstract class AbstractXPortletJspBean extends AdminFeaturesPageJspBean\n{\n}\n' > "$J/src/java/x/web/AbstractXPortletJspBean.java"
expect "JS04: legacy bean through a local base class" 1 "$(vm JS04 FAIL)"

mkdir -p "$J/webapp/js/plugins/x"
printf 'function a(v) {\n\tif (v) {\n\t\treturn 1;\n\t} else {\t{\n\t\treturn 2;\n\t}\n}\n' > "$J/webapp/js/plugins/x/x.js"
expect "JS07: script with an extra brace" 1 "$(vm JS07 FAIL)"
printf 'function a(v) {\n\treturn v ? 1 : 2;\n}\n' > "$J/webapp/js/plugins/x/x.js"
expect "JS07: script that parses" 1 "$(vm JS07 PASS)"

printf 'name=X\nlabel=First\nlabel=Second\n' > "$J/src/java/x/resources/x_messages.properties"
expect "I18N10: key declared twice" 1 "$(vm I18N10 WARN)"
printf 'name=X\nlabel=Second\n' > "$J/src/java/x/resources/x_messages.properties"
expect "I18N10: every key once" 1 "$(vm I18N10 PASS)"
mkdir -p "$J/webapp/WEB-INF/plugins" "$J/src/sql/plugins/x/core"
printf '<plug-in>\n<name>x</name>\n<description>x.name</description>\n<portlet-type-name>x.missing.portlet</portlet-type-name>\n</plug-in>\n' > "$J/webapp/WEB-INF/plugins/x.xml"
printf "INSERT INTO core_admin_right (id_right,name,description) VALUES ('X_RIGHT','x.label','x.missing.right');\n" > "$J/src/sql/plugins/x/core/init_core_x.sql"
expect "I18N02: descriptor and right keys declared nowhere" 1 "$(cd "$J" && bash "$S/verify-migration.sh" . 2>/dev/null | grep -c 'x.missing.portlet\|x.missing.right' | grep -qx 2 && echo 1)"
printf 'name=X\nlabel=Second\nmissing.portlet=P\nmissing.right=R\n' > "$J/src/java/x/resources/x_messages.properties"
expect "I18N02: descriptor and right keys declared" 1 "$(vm I18N02 PASS)"
rm -rf "$J/webapp/WEB-INF/plugins" "$J/src/sql"
printf 'class R {\n    String f( ) { return String.valueOf( ThreadLocalRandom.current( ).nextLong( ) ); }\n}\n' > "$J/src/java/x/business/R.java"
expect "TL01: ThreadLocalRandom is no ThreadLocal" 1 "$(vm TL01 PASS)"
printf 'class R {\n    private static final ThreadLocal<String> T = new ThreadLocal<>( );\n}\n' > "$J/src/java/x/business/R.java"
expect "TL01: ThreadLocal never removed" 1 "$(vm TL01 FAIL)"
rm -f "$J/src/java/x/business/R.java"
printf 'class XJspBean extends MVCAdminJspBean {\n    @View( VIEW_CREATE )\n    public String getCreate( HttpServletRequest request )\n    {\n        return doCreate( request );\n    }\n    @Action( ACTION_CREATE )\n    public String doCreate( HttpServletRequest request )\n    {\n        return null;\n    }\n}\n' > "$J/src/java/x/web/XJspBean.java"
expect "MV05: a view running a do* action" 1 "$(vm MV05 WARN)"
printf 'class XJspBean extends MVCAdminJspBean {\n    @View( VIEW_LIST )\n    public String getList( HttpServletRequest request )\n    {\n        return getConfirmRemove( request );\n    }\n    @Action( ACTION_CONFIRM )\n    public String getConfirmRemove( HttpServletRequest request )\n    {\n        return null;\n    }\n    @Action( ACTION_CREATE )\n    public String doCreate( HttpServletRequest request )\n    {\n        return null;\n    }\n}\n' > "$J/src/java/x/web/XJspBean.java"
expect "MV05: a view showing a confirmation action" 1 "$(vm MV05 PASS)"
rm -f "$J/src/java/x/web/XJspBean.java"
M="$T/module"
mkdir -p "$M/src/java/fr/paris/lutece/plugins/wf/modules/x/resources" "$M/src/java/fr/paris/lutece/plugins/wf/modules/x/web"
printf 'task.title=Task\n' > "$M/src/java/fr/paris/lutece/plugins/wf/modules/x/resources/x_messages.properties"
printf 'class C {\n    private static final String MESSAGE_A = "module.wf.x.task.title";\n    private static final String MESSAGE_B = "module.wf.x.task.missing";\n    private static final String MESSAGE_C = "x.owned.by.plugin.x";\n}\n' > "$M/src/java/fr/paris/lutece/plugins/wf/modules/x/web/C.java"
expect "I18N02: a module checks its module.<plugin>.<module> keys only" 1 "$(cd "$M" && bash "$S/verify-migration.sh" . 2>/dev/null | grep -A3 '\[I18N02\]' | grep -c '^ *module.wf.x.task.missing:')"
expect "I18N02: the plugin's own keys are left to it" 0 "$(cd "$M" && bash "$S/verify-migration.sh" . 2>/dev/null | grep -c 'x.owned.by.plugin.x')"

[ "$fail" -eq 0 ] && echo "PASS: template rules, TD55, TD56, TD57, TD58, TD59, TD60, TD61, DA02, I18N02, I18N07, I18N10, TL01, MV05, JS04, JS07, fix-button-colours"
exit $fail
